$(document).ready(function(){
    $('#content-get').hide();
    $('#content-post').hide();
    $('#content-get-id').hide();
    $('#content-put-id').hide();
    $('#content-delete-id').hide();

    $('#open-close-get').click(function(){
        $('#content-get').slideToggle();
    });
    $('#open-close-post').click(function(){
        $('#content-post').slideToggle();
    });
    $('#open-close-get-id').click(function(){
        $('#content-get-id').slideToggle();
    });
    $('#open-close-put-id').click(function(){
        $('#content-put-id').slideToggle();
    });
    $('#open-close-delete-id').click(function(){
        $('#content-delete-id').slideToggle();
    });
});